name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3  # Updated to v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3  # Updated to v3

      - name: 'Build Service Image'
        uses: docker/build-push-action@v5  # Updated to v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64  # Add this line for multi-platform
          tags: ghcr.io/supadata-ai/mcp:latest
          cache-from: type=registry,ref=ghcr.io/supadata-ai/mcp:latest
          cache-to: type=inline
